version: '3'
services:
   biwenger-api:
      build: .
      restart: always
      expose:
         - 8080
      ports:
         - "8080:8080"
      depends_on:
        - mongodb
   mongodb:
      image: mongo:latest
      volumes:
         - ./data/mongodb:/data/db
      expose:
        - 27017
      ports:
        - "27017:27017"
      restart: always
      command: --smallfiles